name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release -p omd2typst

      - name: Strip binary
        run: strip target/release/omd2typst

      - name: Create release and upload binary
        uses: forgejo/release-action@v1
        with:
          direction: upload
          release-dir: target/release/
          release-files: omd2typst
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          rename-files: |
            omd2typst=omd2typst-linux-x86_64
