[package]
name = "omd2typst-wasm"
version = "0.5.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "WASM bindings for omd2typst-core"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--all-features"]

[dependencies]
omd2typst-core = { path = "../core" }
wasm-bindgen = "0.2"
